## CCFS chunk-server config file

# server configuration
server_id: 8960fbc3-6ded-4d2b-a269-74fd4fa064fe
host: "0.0.0.0"
port: 5000

# path where the files will be stored
upload_path: ~/.ccfs/ccfs-uploads

# metadata server url
metadata_url: http://host.docker.internal:4000

# ping job configuration
ping_interval: 5 # in seconds