FROM rust:buster as planner
WORKDIR /app

RUN cargo install cargo-chef
COPY . .
RUN cargo chef prepare  --recipe-path recipe.json

FROM rust:buster as cacher
WORKDIR /app
RUN cargo install cargo-chef
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json

FROM rust:buster as builder
WORKDIR /app
COPY . .
# Copy over the cached dependencies
COPY --from=cacher /app/target target
COPY --from=cacher /usr/local/cargo /usr/local/cargo
RUN cargo build --release --bin chunk-server

FROM debian:buster as runtime
WORKDIR /app
COPY --from=builder /app/target/release/chunk-server /usr/local/bin
RUN apt-get update && apt-get install -y pkg-config libssl-dev
ENTRYPOINT ["/usr/local/bin/chunk-server"]