## CCFS metadata server config file

# server configuration
id: 0
server_id: dff4981a-c75b-473a-a9de-d8e7506845ae
host: 0.0.0.0
port: 4000

# snapshot job configuration
snapshot_interval: 10 # in seconds
snapshot_dir_path: ~/.ccfs/ccfs-snapshot
snapshot_file_name: snapshot

# replication job configuration
replication_interval: 3 # in seconds