## CCFS metadata server config file

# server configuration
id: 1
server_id: ab542e49-be7f-4483-866a-36514fb551c1
host: 0.0.0.0
port: 4001

# snapshot job configuration
snapshot_interval: 10 # in seconds
snapshot_dir_path: ~/.ccfs/ccfs-snapshot
snapshot_file_name: snapshot1

# replication job configuration
replication_interval: 3 # in seconds